matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .spelling-wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: true
      attributes:
      - title
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'

  sources:
  - 'docs/**/*.md'
  default_encoding: utf-8
