name: PR

on: pull_request

jobs:
  superlinter:
    name: Lint markdown and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true
